---
- name: uninstall apache server
  hosts: localhost
  become: yes
  tasks:
    - name: stop httpd service
      service: name=httpd state=stopped
    - name: uninstall httpd package
      yum: name=httpd state=absent